name: Auto execution

on:
  schedule:
    - cron: '0 5 * * *' # utc+8 13:00
  watch:
    types: [started]
  push:
    branches:
      - source  # may only test
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install regex
        
    - name: Deploy the SSH Key
      env:
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          mkdir -p ~/.ssh
          echo "$GIT_TOKEN" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Clone branch
      run: |
          mkdir ~/source && cd ~/source
          git clone -b source git@github.com:creater303/pic.git
          mkdir ~/main && cd ~/main
          git clone -b main git@github.com:creater303/pic.git --depth 1
          
    - name: Run
      run: |
          cd ~/source/pic/src
          python fetch.py https://raw.githubusercontent.com/gxywy/pixiv-daily/main/README.md
          cp -r `ls ~/source/pic/src/* | grep -Ev 'fetch.py|main.rs' | xargs` ~/main/pic/pictures/
          
    - name: Commit files and push
      run: |
          cd ~/main/pic
          git config --local user.email "lemonmiaow@gmail.com"
          git config --local user.name "creater303"
          git add .
          git commit -m "##update daily rankings##"
          git push
