name: Rust auto execution

on:
  schedule:
    - cron: '0 0 * * *' # utc+8 8:00
  watch:
    types: started
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Clone branch
      run: |
          mkdir ~/source && cd ~/source
          git clone -b source git@github.com:Lemon-miaow/pic.git
          mkdir ~/main && cd ~/main
          git clone -b main git@github.com:Lemon-miaow/pic.git 
    - name: Run
          cd ~/source/pic/compiled
          chmod +x fetch_md
          ./fetch_md https://raw.githubusercontent.com/gxywy/pixiv-daily/main/README.md
          cp -r `ls ~/source/pic/compiled/* | grep -v fetch_md | xargs` ~/main/pic/pictures/
    - name: Commit files
      run: |
          cd ~/main/pic
          git config --local user.email "lemonmiaow@gmail.com"
          git config --local user.name "Lemon-miaow"
          git add .
          git commit -m "##update daily rankings##"
    - name: Push to main branch
      uses:  ad-m/github-push-action@master
      with:
         github_token: ${{ secrets.GIT_TOKEN }}
         branch: main
